services:
  redis:
    image: redis:8.4-alpine
    container_name: redis
    networks:
      - app_network
      
  nginx:
    container_name: nginx
    image: nginx:1.29.4-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./apps:/app
      - ./conf/nginx:/etc/nginx/conf.d/
      # - ./conf/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - app_network
    depends_on:
      - web

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./apps:/app
    environment:
      - CI_ENV=development
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - CI_ENCRYPTION_KEY=${CI_ENCRYPTION_KEY}
      - CI_DB_PASSWORD=${CI_DB_PASSWORD}
      - CI_DEBUG=${CI_DEBUG}
      - CI_MINIFY=${CI_MINIFY}
      - CI_CACHE=${CI_CACHE}
      - CI_MAINTAIN_MODE=${CI_MAINTAIN_MODE}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
      - FB_SECRET=${FB_SECRET}
      - FB_API=${FB_API}
      - GG_SECRET=${GG_SECRET}
      - GG_KEY=${GG_KEY}
      - GG_API=${GG_API}
      - GG_CAPTCHA_SITE_KEY=${GG_CAPTCHA_SITE_KEY}
      - GG_CAPTCHA_SECRET_KEY=${GG_CAPTCHA_SECRET_KEY}
      - JWT_CONSUMER_KEY=${JWT_CONSUMER_KEY}
      - JWT_CONSUMER_SECRET=${JWT_CONSUMER_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PREFIX=${REDIS_PREFIX}
      - YANDEX_TRANSLATE_API_KEY=${YANDEX_TRANSLATE_API_KEY}
    networks:
      - app_network

  mongodb:
    image: mongo:8.2
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # ports:
    #   - "127.0.0.1:27017:27017"
    networks:
      - app_network
    volumes:
      # - ./db/mongod.conf:/etc/mongod.conf
      - mongo_data:/data/db
    deploy: # ThÃªm resource limits
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  mysql:
    container_name: mysql
    image: mariadb:10.5
    restart: always
    command: --max_connections=1000 --wait_timeout=60 --interactive_timeout=60
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
